apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ops-health-data
  namespace: ops-health
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
